[package]
name = "autotyler"
version = "0.2.0"
authors = ["wareya <wareya@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.8"

[profile.release]
lto = true
codegen-units = 1
